### ISSUE TITLE
VNC does no more work with google-chrome 19.0.1084.46 (linux/win)

### ISSUE THREAD

**Issue by moobyfr** [ArchipelProject/Archipel#467]
Since updating to the latest chrome version, the VNC part isn't vorking anymore.
this is not a noVNC issue, as I can still use it, but more something related to the websocket:

012-05-22 11:28:37.823 Cappuccino [trace]: < iq xmlns='jabber:client' from='47ba0d3e-4026-11e1-b114-fead8d4b154e@f.q.d.n/hypervisor' to='admin@f.q.d.n/ArchipelController' id='1686' type='result'>< query xmlns='archipel:virtualmachine:vnc'>< display host='xxx.xxx.xxx.xxx' onlyssl='False' port='5908' supportssl='True' proxy='6908'/>< /query>< /iq> Objective-J.js:365
WebSocket is closed before the connection is established. :1
2012-05-22 11:28:39.821 Cappuccino [info]: noVNC state changed from connect to failed Objective-J.js:365
2012-05-22 11:28:39.821 Cappuccino [error]: disconnected from the VNC screen at xxx.xxx.xxx.xxx:6908 Objective-J.js:365
2012-05-22 11:28:39.873 Cappuccino [info]: noVNC state changed from failed to disconnected 

on the archipel log, the following error is displayed when closing the main chrome window:

  1: handler exception: WSRequestHandler instance has no attribute 'last_code'
  1: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/archipel_agent_virtualmachine_vnc-0.5.0beta-py2.7.egg/archipelagentvirtualmachinevnc/websocket.py", line 709, in top_new_client
    self.client = self.do_handshake(startsock, address)
  File "/usr/local/lib/python2.7/dist-packages/archipel_agent_virtualmachine_vnc-0.5.0beta-py2.7.egg/archipelagentvirtualmachinevnc/websocket.py", line 581, in do_handshake
    if wsh.last_code == 101:
AttributeError: WSRequestHandler instance has no attribute 'last_code'
